    # Generated by Django 4.1.1 on 2022-09-23 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewiev',
            fields=[
                ('id_pole', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.film')),
            ],
        ),
    ]
