# Generated by Django 4.1.1 on 2022-09-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rewiev'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
