# Generated by Django 4.1.1 on 2022-09-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_film_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='image',
            new_name='img',
        ),
    ]
