# Generated by Django 4.1.1 on 2022-09-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_image_film_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='img',
            new_name='image',
        ),
    ]
