# Generated by Django 4.1.1 on 2022-09-29 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_filmcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmcomment',
            name='books',
        ),
        migrations.RemoveField(
            model_name='filmcomment',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='filmcomment',
            name='update_date',
        ),
        migrations.AddField(
            model_name='filmcomment',
            name='films',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='film_comment', to='main.film'),
        ),
    ]
